'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Palawan.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Qry.Artikelnummer,
        '''	   FLOOR(Qry.Menge/A.USER_InhaltKarton) AnzGanzKartons
        '''FROM (SELECT Artikelnummer,
        '''	         SUM(Menge) Menge
        '''      FROM CCPASSBelege B
        '''	     INNER JOIN Cotton.dbo.KHKVKBelegePositionen BP ON (B.Mandant=BP.Mandant
        '''															AND B.BelID=BP.BelID)
        '''      WHERE ErstelltWann BETWEEN @DatumVON AND @DatumBIS
        '''            AND Abgebrochen=0
        '''	  GROUP BY Artikelnummer) Qry
        '''	INNER JOIN Cotton.dbo.KHKARtikel A ON (Qry.Artikelnummer=A.Artikelnummer)
        '''WHERE A.USER_InhaltKarton&gt;0
        '''	 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL1000() As String
            Get
                Return ResourceManager.GetString("SQL1000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT E.Mandant,
        '''       CASE 
        '''	      WHEN P.Halle=&apos;A&apos; THEN CONCAT(E.Halle,&apos;.&apos;,E.Reihe,&apos;_&apos;,P.Position,&apos;.&apos;, E.Ebene)
        '''		  WHEN P.Halle =&apos;B&apos; THEN CONCAT(E.Halle,&apos;.&apos;,E.Reihe,&apos;_&apos;,P.Position,&apos;.&apos;, E.Ebene)
        '''	      ELSE COALESCE(LegacyLocator,  CONCAT(E.Halle,&apos;.&apos;,E.Reihe,&apos;_&apos;,P.Position,&apos;.&apos;, E.Ebene))
        '''	   END LegacyLocator,
        '''	   E.Halle,
        '''	   E.Reihe,
        '''	   P.Ebene,
        '''	   P.Position,
        '''	   Breite,
        '''	   Bodenhoehe,
        '''	   Fachhoehe,
        '''	   L.Bezeichnung Logik,
        '''	   R.ReiheModulo,
        '''	   R.Tiefe
        '''FROM LocatorReihenEbenenPo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL1001() As String
            Get
                Return ResourceManager.GetString("SQL1001", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT E.Mandant,
        '''       CASE 
        '''	      WHEN P.Halle=&apos;A&apos; THEN CONCAT(E.Halle,&apos;.&apos;,E.Reihe,&apos;_&apos;,P.Position,&apos;.&apos;, E.Ebene)
        '''		  WHEN P.Halle =&apos;B&apos; THEN CONCAT(E.Halle,&apos;.&apos;,E.Reihe,&apos;_&apos;,P.Position,&apos;.&apos;, E.Ebene)
        '''	      ELSE COALESCE(LegacyLocator,  CONCAT(E.Halle,&apos;.&apos;,E.Reihe,&apos;_&apos;,P.Position,&apos;.&apos;, E.Ebene))
        '''	   END LegacyLocator,
        '''	   E.Halle,
        '''	   E.Reihe,
        '''	   P.Ebene,
        '''	   P.Position,
        '''	   Breite,
        '''	   Bodenhoehe,
        '''	   Fachhoehe,
        '''	   L.Bezeichnung Logik,
        '''	   R.ReiheModulo,
        '''	   R.Tiefe
        '''FROM LocatorReihenEbenenPo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL1002() As String
            Get
                Return ResourceManager.GetString("SQL1002", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Artikelnummer,
        '''	   CASE
        '''	      WHEN CHARINDEX(&apos;  -&apos;,Bezeichnung1,0)&gt;0
        '''		     THEN LEFT(Bezeichnung1,CHARINDEX(&apos;  -&apos;,Bezeichnung1,0)-1)
        '''			 ELSE Bezeichnung1
        '''	   END Bezeichnung1,
        '''	   F.Bezeichnung Farbe,
        '''	   G.Bezeichnung Groesse,
        '''	   USER_DTKommLager,
        '''	   ROW_NUMBER() OVER(PARTITION BY USER_DTKommLager ORDER BY RIGHT(Artikelnummer,2) DESC) LOC_SKUCount
        '''FROM Cotton.dbo.KHKArtikel A
        '''	LEFT JOIN (SELECT Mandant,
        '''	                  Gruppe,
        '''	                  Bezeichnung
        '''			   FROM Cotton.db [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property SQL1003() As String
            Get
                Return ResourceManager.GetString("SQL1003", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT MIN(Artikelnummer) Artikelnummer,
        '''	   USER_KommLagerplatzEffektiv LocatorEffektiv
        '''FROM Cotton.dbo.KHKArtikel
        '''WHERE Aktiv&lt;&gt;0
        '''      AND LEFT(Artikelnummer,2) &lt;&apos;90&apos;
        '''	  AND LEN(USER_KommLagerplatzEffektiv) = 9
        '''GROUP BY USER_KommLagerplatzEffektiv
        '''ORDER BY USER_KommLagerplatzEffektiv.
        '''</summary>
        Friend ReadOnly Property SQL1004() As String
            Get
                Return ResourceManager.GetString("SQL1004", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT Halle,
        '''	   Reihe,
        '''	   Ebene,
        '''	   Locator,
        '''	   L.Fachhoehe,
        '''	   ReiheModulo	
        '''FROM CCLEAP.dbo.LocFlat L
        '''WHERE L.PlatztypOverride=2
        '''ORDER BY Halle,
        '''	     Ebene,
        '''		 Reihe,
        '''		 CASE WHEN ReiheModulo=-1 THEN Position END DESC,
        '''		 CASE WHEN ReiheModulo=1 THEN Position END ASC.
        '''</summary>
        Friend ReadOnly Property SQL1005() As String
            Get
                Return ResourceManager.GetString("SQL1005", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
